# Dockerfile.head
FROM python:3.10-slim

WORKDIR /app

# System dependencies (minimal)
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install minimal dependencies
COPY requirements-head.txt .
RUN pip install -r requirements-head.txt

# Copy source code
COPY src/ /app/src/
COPY client/ /app/client/

# Command to run when container starts
#CMD ["python", "src/main.py", "--head-only"]